CREATE DATABASE IF NOT EXISTS `ks-scmc`
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;	-- utf8mb4_0900_ai_ci utf8_general_ci

USE `ks-scmc`;

CREATE TABLE IF NOT EXISTS `user_infos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
  `password_en` VARCHAR(255) NOT NULL DEFAULT '',
  `role` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(20) NOT NULL DEFAULT 0,
  `updated_at` INT(20) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1000;

CREATE TABLE IF NOT EXISTS `user_sessions` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `session_key` VARCHAR(255) NOT NULL DEFAULT '',
  `source` VARCHAR(255) NOT NULL DEFAULT '',
  `expired_at` INT(20) NOT NULL DEFAULT 0,
  `created_at` INT(20) NOT NULL DEFAULT 0,
  `updated_at` INT(20) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `user_operation_history` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `operator` VARCHAR(255) NOT NULL DEFAULT '',
  `target` VARCHAR(255) NOT NULL DEFAULT '',
  `operation` VARCHAR(255) NOT NULL DEFAULT '',	/* signup login logout alter_password */
  `source` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(20) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `node_infos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
  `address` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
  `comment` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` INT(20) NOT NULL DEFAULT 0,
  `updated_at` INT(20) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1;

/*
CREATE TABLE IF NOT EXISTS `image_infos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
  `version` VARCHAR(255) NOT NULL DEFAULT '' UNIQUE,
  `file_size` VARCHAR(255) NOT NULL DEFAULT '',
  `file_type` VARCHAR(255) NOT NULL DEFAULT '',
  `file_data` LONGBLOB NOT NULL,
  `checksum`
  `created_at` INT(20) NOT NULL DEFAULT 0,
  `updated_at` INT(20) NOT NULL DEFAULT 0
) ENGINE=InnoDB AUTO_INCREMENT=1;
*/
