// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package network

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error)
	ListIPtables(ctx context.Context, in *ListIPtablesRequest, opts ...grpc.CallOption) (*ListIPtablesReply, error)
	EnableIPtables(ctx context.Context, in *EnableIPtablesRequest, opts ...grpc.CallOption) (*EnableIPtablesReply, error)
	CreateIPtables(ctx context.Context, in *CreateIPtablesRequest, opts ...grpc.CallOption) (*CreateIPtablesReply, error)
	ModifyIPtables(ctx context.Context, in *ModifyIPtablesRequest, opts ...grpc.CallOption) (*ModifyIPtablesReply, error)
	RemoveIPtables(ctx context.Context, in *RemoveIPtablesRequest, opts ...grpc.CallOption) (*RemoveIPtablesReply, error)
	// not implemented
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveReply, error)
}

type networkClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkClient(cc grpc.ClientConnInterface) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/network.Network/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error) {
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, "/network.Network/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error) {
	out := new(DisconnectReply)
	err := c.cc.Invoke(ctx, "/network.Network/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) ListIPtables(ctx context.Context, in *ListIPtablesRequest, opts ...grpc.CallOption) (*ListIPtablesReply, error) {
	out := new(ListIPtablesReply)
	err := c.cc.Invoke(ctx, "/network.Network/ListIPtables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) EnableIPtables(ctx context.Context, in *EnableIPtablesRequest, opts ...grpc.CallOption) (*EnableIPtablesReply, error) {
	out := new(EnableIPtablesReply)
	err := c.cc.Invoke(ctx, "/network.Network/EnableIPtables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) CreateIPtables(ctx context.Context, in *CreateIPtablesRequest, opts ...grpc.CallOption) (*CreateIPtablesReply, error) {
	out := new(CreateIPtablesReply)
	err := c.cc.Invoke(ctx, "/network.Network/CreateIPtables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) ModifyIPtables(ctx context.Context, in *ModifyIPtablesRequest, opts ...grpc.CallOption) (*ModifyIPtablesReply, error) {
	out := new(ModifyIPtablesReply)
	err := c.cc.Invoke(ctx, "/network.Network/ModifyIPtables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) RemoveIPtables(ctx context.Context, in *RemoveIPtablesRequest, opts ...grpc.CallOption) (*RemoveIPtablesReply, error) {
	out := new(RemoveIPtablesReply)
	err := c.cc.Invoke(ctx, "/network.Network/RemoveIPtables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/network.Network/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveReply, error) {
	out := new(RemoveReply)
	err := c.cc.Invoke(ctx, "/network.Network/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
// All implementations must embed UnimplementedNetworkServer
// for forward compatibility
type NetworkServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
	Connect(context.Context, *ConnectRequest) (*ConnectReply, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error)
	ListIPtables(context.Context, *ListIPtablesRequest) (*ListIPtablesReply, error)
	EnableIPtables(context.Context, *EnableIPtablesRequest) (*EnableIPtablesReply, error)
	CreateIPtables(context.Context, *CreateIPtablesRequest) (*CreateIPtablesReply, error)
	ModifyIPtables(context.Context, *ModifyIPtablesRequest) (*ModifyIPtablesReply, error)
	RemoveIPtables(context.Context, *RemoveIPtablesRequest) (*RemoveIPtablesReply, error)
	// not implemented
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Remove(context.Context, *RemoveRequest) (*RemoveReply, error)
	mustEmbedUnimplementedNetworkServer()
}

// UnimplementedNetworkServer must be embedded to have forward compatible implementations.
type UnimplementedNetworkServer struct {
}

func (UnimplementedNetworkServer) List(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNetworkServer) Connect(context.Context, *ConnectRequest) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNetworkServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedNetworkServer) ListIPtables(context.Context, *ListIPtablesRequest) (*ListIPtablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIPtables not implemented")
}
func (UnimplementedNetworkServer) EnableIPtables(context.Context, *EnableIPtablesRequest) (*EnableIPtablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableIPtables not implemented")
}
func (UnimplementedNetworkServer) CreateIPtables(context.Context, *CreateIPtablesRequest) (*CreateIPtablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIPtables not implemented")
}
func (UnimplementedNetworkServer) ModifyIPtables(context.Context, *ModifyIPtablesRequest) (*ModifyIPtablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyIPtables not implemented")
}
func (UnimplementedNetworkServer) RemoveIPtables(context.Context, *RemoveIPtablesRequest) (*RemoveIPtablesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveIPtables not implemented")
}
func (UnimplementedNetworkServer) Create(context.Context, *CreateRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNetworkServer) Remove(context.Context, *RemoveRequest) (*RemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedNetworkServer) mustEmbedUnimplementedNetworkServer() {}

// UnsafeNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServer will
// result in compilation errors.
type UnsafeNetworkServer interface {
	mustEmbedUnimplementedNetworkServer()
}

func RegisterNetworkServer(s grpc.ServiceRegistrar, srv NetworkServer) {
	s.RegisterService(&Network_ServiceDesc, srv)
}

func _Network_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_ListIPtables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIPtablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).ListIPtables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/ListIPtables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).ListIPtables(ctx, req.(*ListIPtablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_EnableIPtables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableIPtablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).EnableIPtables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/EnableIPtables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).EnableIPtables(ctx, req.(*EnableIPtablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_CreateIPtables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIPtablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).CreateIPtables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/CreateIPtables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).CreateIPtables(ctx, req.(*CreateIPtablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_ModifyIPtables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyIPtablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).ModifyIPtables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/ModifyIPtables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).ModifyIPtables(ctx, req.(*ModifyIPtablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_RemoveIPtables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIPtablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).RemoveIPtables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/RemoveIPtables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).RemoveIPtables(ctx, req.(*RemoveIPtablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.Network/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Network_ServiceDesc is the grpc.ServiceDesc for Network service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Network_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Network_List_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Network_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Network_Disconnect_Handler,
		},
		{
			MethodName: "ListIPtables",
			Handler:    _Network_ListIPtables_Handler,
		},
		{
			MethodName: "EnableIPtables",
			Handler:    _Network_EnableIPtables_Handler,
		},
		{
			MethodName: "CreateIPtables",
			Handler:    _Network_CreateIPtables_Handler,
		},
		{
			MethodName: "ModifyIPtables",
			Handler:    _Network_ModifyIPtables_Handler,
		},
		{
			MethodName: "RemoveIPtables",
			Handler:    _Network_RemoveIPtables_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Network_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Network_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}
